DROP TABLE T1;

CREATE TABLE T1
(
    DESCRIPTION VARCHAR2(20 CHAR)
);

INSERT INTO T1 VALUES ('descr 1');

SET AUTOTRACE ON

SELECT * FROM T1 WHERE ROWID = (SELECT ROWID FROM T1 WHERE DESCRIPTION = 'descr 1');

oracle sql cost-based