DROP TABLE T_NON_DEFERRABLE;
DROP TABLE T_DEFERRABLE;

CREATE TABLE T_NON_DEFERRABLE
(
NAME VARCHAR2(255 CHAR)
);

CREATE TABLE T_DEFERRABLE
(
NAME VARCHAR2(255 CHAR)
);

ALTER TABLE T_NON_DEFERRABLE ADD CONSTRAINT T_NON_DEFERRABLE_UNIQUE UNIQUE (NAME);
ALTER TABLE T_DEFERRABLE ADD CONSTRAINT T_DEFERRABLE_UNIQUE UNIQUE (NAME) INITIALLY DEFERRED DEFERRABLE;

INSERT INTO T_NON_DEFERRABLE VALUES ('1'); -- fails here
INSERT INTO T_NON_DEFERRABLE VALUES ('1');

ROLLBACK;

INSERT INTO T_DEFERRABLE VALUES ('1'); 
INSERT INTO T_DEFERRABLE VALUES ('1');

COMMIT; -- fails here

SELECT * FROM T_NON_DEFERRABLE;
SELECT * FROM T_DEFERRABLE;