-- this example shows deferrable constaint use cases
-- we can delete parent record from table before transaction commit

DROP TABLE T_NON_DEFERRABLE_CHILD;
DROP TABLE T_DEFERRABLE_CHILD;
DROP TABLE T_NON_DEFERRABLE_PARENT;
DROP TABLE T_DEFERRABLE_PARENT;


CREATE TABLE T_DEFERRABLE_PARENT
(
    ID NUMBER,
    NAME VARCHAR2(10 CHAR)
);

CREATE TABLE T_DEFERRABLE_CHILD
(
    ID NUMBER,
    NAME VARCHAR2(10 CHAR),
    LINK_TO_PARENT NUMBER
);

CREATE TABLE T_NON_DEFERRABLE_PARENT
(
    ID NUMBER,
    NAME VARCHAR2(10 CHAR)
);

CREATE TABLE T_NON_DEFERRABLE_CHILD
(
    ID NUMBER,
    NAME VARCHAR2(10 CHAR),
    LINK_TO_PARENT NUMBER
);

ALTER TABLE T_DEFERRABLE_PARENT ADD CONSTRAINT T_DEFERRABLE_PARENT_FK PRIMARY KEY (ID);
ALTER TABLE T_NON_DEFERRABLE_PARENT ADD CONSTRAINT T_NON_DEFERRABLE_PARENT_FK PRIMARY KEY (ID);

ALTER TABLE T_DEFERRABLE_CHILD ADD CONSTRAINT T_DEFERRABLE_CHILD_FK_1 FOREIGN KEY (LINK_TO_PARENT) REFERENCES T_DEFERRABLE_PARENT (ID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE T_NON_DEFERRABLE_CHILD ADD CONSTRAINT T_NON_DEFERRABLE_CHILD_FK_2 FOREIGN KEY (LINK_TO_PARENT) REFERENCES T_NON_DEFERRABLE_PARENT (ID);

--- DEF
INSERT INTO T_DEFERRABLE_PARENT VALUES (2, 'a');
INSERT INTO T_DEFERRABLE_CHILD VALUES (2, 'a', 2);

DELETE FROM T_DEFERRABLE_PARENT WHERE ID = 2; -- successfully deleted

COMMIT; -- contraint violation strikes here

-- NON_DEF

INSERT INTO T_NON_DEFERRABLE_PARENT VALUES (2, 'a');
INSERT INTO T_NON_DEFERRABLE_CHILD VALUES (2, 'a', 2);

DELETE FROM T_NON_DEFERRABLE_PARENT WHERE ID = 2; -- constraint violation strikes here