PAUSE This script will DROP tables, press CTRL+C to break

DROP TABLE N;
DROP TABLE NEW_TABLE1;
DROP TABLE NEW_TABLE_WITHOUT_VALUES;
DROP TABLE NEW_TABLE_CUSTOM_COL_NAMES;
DROP TABLE OLD_TABLE;
DROP TABLE NEW_TABLE;

CREATE TABLE OLD_TABLE
(
	OLD_TABLE_KEY number,
	OLD_TABLE_VALUE varchar(20 CHAR)
);

INSERT INTO OLD_TABLE VALUES (0, 'foo');
INSERT INTO OLD_TABLE VALUES (1, 'bar');
INSERT INTO OLD_TABLE VALUES (2, 'qwe');

CREATE TABLE NEW_TABLE AS (SELECT * FROM OLD_TABLE);
--where no need to copy from old table:
CREATE TABLE NEW_TABLE_WITHOUT_VALUES AS (SELECT * FROM OLD_TABLE WHERE 1=2); 
--custom column names:
CREATE TABLE NEW_TABLE_CUSTOM_COL_NAMES AS (SELECT OLD_TABLE_KEY NEW_TABLE_KEY FROM OLD_TABLE);

SELECT * FROM NEW_TABLE;
SELECT * FROM NEW_TABLE_WITHOUT_VALUES;
SELECT * FROM NEW_TABLE_CUSTOM_COL_NAMES;