DROP TABLE V;
DROP VIEW V_VIEW;

CREATE TABLE V
(
	V_KEY number,
	V_VALUE varchar(10 char)
);

INSERT INTO V VALUES(2, 'foo');
INSERT INTO V VALUES(3, 'bar');
INSERT INTO V VALUES(7, 'bar');

--same columns:
CREATE VIEW V_VIEW AS SELECT * FROM V WHERE V_VALUE = 'bar';

--custom field names:
CREATE VIEW V_VIEW2(VIEW_COL_1, VIEW_COL2) AS SELECT COUNT(*), V_VALUE FROM V GROUP BY V_VALUE;

SELECT * FROM V_VIEW;
SELECT * FROM V_VIEW2;