PAUSE This script will DROP tables, press CTRL+C to break

DROP TABLE D;

CREATE TABLE D
(
	D_KEY number,
	D_VALUE varchar(10 char)
);

INSERT INTO D VALUES(0, 'FOO');
INSERT INTO D VALUES(0, 'FOO');
INSERT INTO D VALUES(1, 'FOO');
INSERT INTO D VALUES(2, 'FOO');
INSERT INTO D VALUES(3, 'QWE');
INSERT INTO D VALUES(3, 'QWE');
INSERT INTO D VALUES(3, 'BAR');
INSERT INTO D VALUES(3, null);
INSERT INTO D VALUES(3, null);
INSERT INTO D VALUES(4, null);

SELECT DISTINCT D_KEY, D_VALUE FROM D;

SELECT DISTINCT D_VALUE FROM D;

--In Oracle, the DISTINCT clause doesn't ignore NULL values