-- https://oracle-base.com/articles/misc/join-elimination


DROP TABLE T2;
DROP TABLE T1;

CREATE TABLE T1
(
    ID NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE T1 ADD CONSTRAINT PK_T1 PRIMARY KEY(ID);

INSERT INTO T1 VALUES (0, 'Jack');
INSERT INTO T1 VALUES (1, 'Bob');

CREATE TABLE T2
(
    ID NUMBER NOT NULL,
    PARENT_ID NUMBER,
    DESCRIPTION VARCHAR2(20 CHAR) NOT NULL
);

INSERT INTO T2 VALUES (0, 0, 'Oscar');
INSERT INTO T2 VALUES (0, 0, 'John');
INSERT INTO T2 VALUES (1, 1, 'Olivia');
INSERT INTO T2 VALUES (1, 1, 'Eleanor');

SET AUTOTRACE TRACEONLY

SELECT child.description FROM T2 child JOIN T1 parent ON child.PARENT_ID = parent.ID;

ALTER TABLE T2 ADD CONSTRAINT FK_T2_T1_001 FOREIGN KEY(PARENT_ID) REFERENCES T1(ID);

SELECT child.description FROM T2 child JOIN T1 parent ON child.PARENT_ID = parent.ID;


oracle sql cost-based