


DROP TABLE T1;

CREATE TABLE T1
(
    IDX INTEGER,
    NAME VARCHAR2(100 CHAR)
);

ALTER TABLE T1 ADD CONSTRAINT T1_PK PRIMARY KEY (IDX);

CREATE INDEX T1_IDX ON T1(NAME);

INSERT INTO T1 VALUES (0, 'Maria');
INSERT INTO T1 VALUES (1, 'John');
INSERT INTO T1 VALUES (2, 'Tatiana');
INSERT INTO T1 VALUES (3, 'Elena');
INSERT INTO T1 VALUES (4, 'Chi');
INSERT INTO T1 VALUES (5, 'Peter');

PROMPT IN QUERY


SET AUTOTRACE ON

SELECT * FROM T1 WHERE NAME IN ('Maria', 'Peter');

PROMPT OR QUERY

SELECT * 
FROM 
    T1
WHERE
    NAME = 'Maria'
OR
    NAME = 'Peter';


oracle sql cost-based