DROP TABLE T2;
DROP TABLE T1;

CREATE TABLE T1
(
    ID NUMBER,
    DESCRIPTION VARCHAR2(10 CHAR)
);

CREATE TABLE T2
(
    ID NUMBER,
    T1_ID NUMBER,
    DESCRIPTION VARCHAR2(10 CHAR)
);

INSERT INTO T1 VALUES(0, 'Enstein');
INSERT INTO T1 VALUES(1, 'Bohr');

INSERT INTO T2 VALUES(0, 0, 'Copley');
INSERT INTO T2 VALUES(1, 1, 'Nobel');

SET AUTOTRACE ON

PROMPT USUAL JOIN

SELECT * FROM T2 table2 JOIN T1 table1 ON table1.id = table2.T1_ID;

PROMPT SUBQUERY

SELECT * FROM T2 WHERE T1_ID IN (SELECT ID FROM T1);


oracle sql cost-based