DROP TABLE T1;

CREATE TABLE T1
(
NAME VARCHAR2(256 CHAR)
);

INSERT INTO T1 VALUES ('Vasia');
INSERT INTO T1 VALUES ('Vasia2');
INSERT INTO T1 VALUES ('Vasia3');
INSERT INTO T1 VALUES ('Vasia4');
INSERT INTO T1 VALUES ('Vasia5');

SET AUTOTRACE ON

SELECT * FROM T1;